
CREATE TABLE IF NOT EXISTS operations (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES users (id),
    type VARCHAR(100) NOT NULL,
    symbol VARCHAR(100) NOT NULL,
    price FLOAT(32) DEFAULT 0,
    quantity int NOT NULL
);