
CREATE TABLE IF NOT EXISTS operations (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL REFERENCES users (id),
    type VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    purchase_price FLOAT(32) DEFAULT 0,
    amount int NOT NULL
);