port: "8000"

logLevel: "debug"

dsn: "user=postgres password=1234 dbname=postgres host=db port=5432 sslmode=disable"

migrationsPath: "migrations"

salt: "asdasdasdas"

jwt_secret: "asdasdasdsa"

api_access_key: "asdasdasdas"
